"""add embedings table

Revision ID: 4b36d1608841
Revises: 162b978e0a4d
Create Date: 2025-09-16 19:15:41.446962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4b36d1608841'
down_revision: Union[str, Sequence[str], None] = '162b978e0a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_embeddings_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_embeddings')),
    sa.UniqueConstraint('message_id', name=op.f('uq_message_embeddings_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_embeddings')
    # ### end Alembic commands ###
