"""accomidate table to allow adding chunks

Revision ID: d5f487d7fdb9
Revises: debd0bfaf28f
Create Date: 2025-09-16 19:40:41.125470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd5f487d7fdb9'
down_revision: Union[str, Sequence[str], None] = 'debd0bfaf28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_embeddings', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('message_embeddings', sa.Column('text_chunk', sa.String(), nullable=False))
    op.alter_column('message_embeddings', 'embedding',
               existing_type=Vector(dim=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_embeddings', 'embedding',
               existing_type=Vector(dim=1024),
               nullable=True)
    op.drop_column('message_embeddings', 'text_chunk')
    op.drop_column('message_embeddings', 'chunk_index')
    # ### end Alembic commands ###
