"""allow a message to have multiple embeddings

Revision ID: debd0bfaf28f
Revises: 4b36d1608841
Create Date: 2025-09-16 19:31:33.243324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debd0bfaf28f'
down_revision: Union[str, Sequence[str], None] = '4b36d1608841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_message_embeddings_message_id'), 'message_embeddings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_message_embeddings_message_id'), 'message_embeddings', ['message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
