version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg17
    container_name: chatbot_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: chatbot_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d   
volumes:
  pgdata:
