name: CI Pipeline

on:
  pull_request:
    branches: [ecr_ci_cd]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.PULL_REQUEST_AWS_ROLE_TO_ASSUME}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create .env file
        run: |
          cat > .env <<EOF
          OPENAI_API_KEY=${OPENAI_API_KEY:-${{ secrets.OPENAI_API_KEY }}}
          COGNITO_REGION=${COGNITO_REGION:-${{ secrets.COGNITO_REGION }}}
          COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID:-${{ secrets.COGNITO_USER_POOL_ID }}}
          COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID:-${{ secrets.COGNITO_APP_CLIENT_ID }}}
          COGNITO_APP_CLIENT_SECRET=${COGNITO_APP_CLIENT_SECRET:-${{ secrets.COGNITO_APP_CLIENT_SECRET }}}
          EOF

      - name: Build and test
        run: make test
